/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BehaviorIntervention: typeof import('./src/components/BehaviorIntervention.vue')['default']
    CarbonIcon: typeof import('./src/components/CarbonIcon.vue')['default']
    DemoBlock: typeof import('./src/components/DemoBlock.vue')['default']
    FundCompareTable: typeof import('./src/components/xiaoji-assistant/cards/FundCompareTable.vue')['default']
    MonthlyReport: typeof import('./src/components/MonthlyReport.vue')['default']
    MultiChoice: typeof import('./src/components/xiaoji-assistant/cards/MultiChoice.vue')['default']
    SingleChoice: typeof import('./src/components/xiaoji-assistant/cards/SingleChoice.vue')['default']
    SliderCard: typeof import('./src/components/xiaoji-assistant/cards/SliderCard.vue')['default']
    WdBadge: typeof import('@wot-ui/ui/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdEmpty: typeof import('@wot-ui/ui/components/wd-empty/wd-empty.vue')['default']
    WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['default']
    WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdProgress: typeof import('@wot-ui/ui/components/wd-progress/wd-progress.vue')['default']
    WdSearch: typeof import('@wot-ui/ui/components/wd-search/wd-search.vue')['default']
    WdSelectPicker: typeof import('@wot-ui/ui/components/wd-select-picker/wd-select-picker.vue')['default']
    WdSlider: typeof import('@wot-ui/ui/components/wd-slider/wd-slider.vue')['default']
    WdSwipeAction: typeof import('@wot-ui/ui/components/wd-swipe-action/wd-swipe-action.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTab: typeof import('@wot-ui/ui/components/wd-tab/wd-tab.vue')['default']
    WdTabs: typeof import('@wot-ui/ui/components/wd-tabs/wd-tabs.vue')['default']
    WdTag: typeof import('@wot-ui/ui/components/wd-tag/wd-tag.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
    XiaojiAssistant: typeof import('./src/components/xiaoji-assistant/index.vue')['default']
  }
}
