/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FundCompareTable: typeof import('./src/components/xiaoji-assistant/cards/FundCompareTable.vue')['default']
    MultiChoice: typeof import('./src/components/xiaoji-assistant/cards/MultiChoice.vue')['default']
    SingleChoice: typeof import('./src/components/xiaoji-assistant/cards/SingleChoice.vue')['default']
    SliderCard: typeof import('./src/components/xiaoji-assistant/cards/SliderCard.vue')['default']
    XiaojiAssistant: typeof import('./src/components/xiaoji-assistant/index.vue')['default']
  }
}
