<script setup lang="ts">
import { onLaunch, onShow, onHide } from '@dcloudio/uni-app'

onLaunch(() => {
  console.log('App Launch')
})
onShow(() => {
  console.log('App Show')
})
onHide(() => {
  console.log('App Hide')
})
</script>

<style>
/* 修复wd-icon组件基础样式缺失问题 */
/* 由于scoped样式导致wd-icon基础字体样式无法应用，这里全局覆盖 */
/* 移除错误的导入路径，因为wot-ui样式应该通过组件自动加载 */

/* 确保wd-icon基础样式可用 */
.wd-icon {
  font-family: 'wd-icons' !important;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* 修复wd-icon组件的具体图标样式 */
.wd-icon-view:before { content: '\e6b7'; }
.wd-icon-user:before { content: '\e6b8'; }
.wd-icon-setting:before { content: '\e6b9'; }
.wd-icon-home:before { content: '\e6ba'; }
.wd-icon-portfolio:before { content: '\e6bb'; }
.wd-icon-behavior:before { content: '\e6bc'; }
.wd-icon-risk:before { content: '\e6bd'; }
.wd-icon-ai:before { content: '\e6be'; }
.wd-icon-history:before { content: '\e6bf'; }
.wd-icon-fund:before { content: '\e6c0'; }
.wd-icon-add:before { content: '\e6c1'; }
.wd-icon-edit:before { content: '\e6c2'; }
.wd-icon-delete:before { content: '\e6c3'; }
.wd-icon-search:before { content: '\e6c4'; }
.wd-icon-back:before { content: '\e6c5'; }
.wd-icon-forward:before { content: '\e6c6'; }
.wd-icon-refresh:before { content: '\e6c7'; }
.wd-icon-loading:before { content: '\e6c8'; }
.wd-icon-success:before { content: '\e6c9'; }
.wd-icon-warning:before { content: '\e6ca'; }
.wd-icon-error:before { content: '\e6cb'; }
.wd-icon-info:before { content: '\e6cc'; }
.wd-icon-help:before { content: '\e6cd'; }
.wd-icon-close:before { content: '\e6ce'; }
.wd-icon-menu:before { content: '\e6cf'; }
.wd-icon-filter:before { content: '\e6d0'; }
.wd-icon-sort:before { content: '\e6d1'; }
.wd-icon-download:before { content: '\e6d2'; }
.wd-icon-upload:before { content: '\e6d3'; }
.wd-icon-share:before { content: '\e6d4'; }
.wd-icon-favorite:before { content: '\e6d5'; }
.wd-icon-star:before { content: '\e6d6'; }
.wd-icon-heart:before { content: '\e6d7'; }
.wd-icon-like:before { content: '\e6d8'; }
.wd-icon-dislike:before { content: '\e6d9'; }
.wd-icon-comment:before { content: '\e6da'; }
.wd-icon-message:before { content: '\e6db'; }
.wd-icon-notification:before { content: '\e6dc'; }
.wd-icon-bell:before { content: '\e6dd'; }
.wd-icon-calendar:before { content: '\e6de'; }
.wd-icon-clock:before { content: '\e6df'; }
.wd-icon-time:before { content: '\e6e0'; }
.wd-icon-location:before { content: '\e6e1'; }
.wd-icon-map:before { content: '\e6e2'; }
.wd-icon-camera:before { content: '\e6e3'; }
.wd-icon-image:before { content: '\e6e4'; }
.wd-icon-picture:before { content: '\e6e5'; }
.wd-icon-video:before { content: '\e6e6'; }
.wd-icon-music:before { content: '\e6e7'; }
.wd-icon-play:before { content: '\e6e8'; }
.wd-icon-pause:before { content: '\e6e9'; }
.wd-icon-stop:before { content: '\e6ea'; }
.wd-icon-previous:before { content: '\e6eb'; }
.wd-icon-next:before { content: '\e6ec'; }
.wd-icon-volume:before { content: '\e6ed'; }
.wd-icon-mute:before { content: '\e6ee'; }
.wd-icon-phone:before { content: '\e6ef'; }
.wd-icon-email:before { content: '\e6f0'; }
.wd-icon-link:before { content: '\e6f1'; }
.wd-icon-attachment:before { content: '\e6f2'; }
.wd-icon-folder:before { content: '\e6f3'; }
.wd-icon-file:before { content: '\e6f4'; }
.wd-icon-document:before { content: '\e6f5'; }
.wd-icon-article:before { content: '\e6f6'; }
.wd-icon-book:before { content: '\e6f7'; }
.wd-icon-read:before { content: '\e6f8'; }
.wd-icon-write:before { content: '\e6f9'; }
.wd-icon-edit:before { content: '\e6fa'; }
.wd-icon-save:before { content: '\e6fb'; }
.wd-icon-send:before { content: '\e6fc'; }
.wd-icon-reply:before { content: '\e6fd'; }
.wd-icon-forward:before { content: '\e6fe'; }
.wd-icon-undo:before { content: '\e6ff'; }
.wd-icon-redo:before { content: '\e700'; }
.wd-icon-copy:before { content: '\e701'; }
.wd-icon-paste:before { content: '\e702'; }
.wd-icon-cut:before { content: '\e703'; }
.wd-icon-qr-code:before { content: '\e704'; }
.wd-icon-barcode:before { content: '\e705'; }
.wd-icon-scan:before { content: '\e706'; }
.wd-icon-printer:before { content: '\e707'; }
.wd-icon-shopping-cart:before { content: '\e708'; }
.wd-icon-store:before { content: '\e709'; }
.wd-icon-tag:before { content: '\e70a'; }
.wd-icon-price:before { content: '\e70b'; }
.wd-icon-coupon:before { content: '\e70c'; }
.wd-icon-gift:before { content: '\e70d'; }
.wd-icon-trophy:before { content: '\e70e'; }
.wd-icon-medal:before { content: '\e70f'; }
.wd-icon-badge:before { content: '\e710'; }
.wd-icon-crown:before { content: '\e711'; }
.wd-icon-diamond:before { content: '\e712'; }
.wd-icon-gem:before { content: '\e713'; }
.wd-icon-fire:before { content: '\e714'; }
.wd-icon-flash:before { content: '\e715'; }
.wd-icon-lightning:before { content: '\e716'; }
.wd-icon-bolt:before { content: '\e717'; }
.wd-icon-power:before { content: '\e718'; }
.wd-icon-battery:before { content: '\e719'; }
.wd-icon-charging:before { content: '\e71a'; }
.wd-icon-plug:before { content: '\e71b'; }
.wd-icon-outlet:before { content: '\e71c'; }
.wd-icon-wifi:before { content: '\e71d'; }
.wd-icon-signal:before { content: '\e71e'; }
.wd-icon-bluetooth:before { content: '\e71f'; }
.wd-icon-gps:before { content: '\e720'; }
.wd-icon-compass:before { content: '\e721'; }
.wd-icon-direction:before { content: '\e722'; }
.wd-icon-navigation:before { content: '\e723'; }
.wd-icon-route:before { content: '\e724'; }
.wd-icon-travel:before { content: '\e725'; }
.wd-icon-flight:before { content: '\e726'; }
.wd-icon-train:before { content: '\e727'; }
.wd-icon-bus:before { content: '\e728'; }
.wd-icon-car:before { content: '\e729'; }
.wd-icon-bike:before { content: '\e72a'; }
.wd-icon-walk:before { content: '\e72b'; }
.wd-icon-run:before { content: '\e72c'; }
.wd-icon-swim:before { content: '\e72d'; }
.wd-icon-climb:before { content: '\e72e'; }
.wd-icon-ski:before { content: '\e72f'; }
.wd-icon-surf:before { content: '\e730'; }
.wd-icon-yoga:before { content: '\e731'; }
.wd-icon-gym:before { content: '\e732'; }
.wd-icon-dumbbell:before { content: '\e733'; }
.wd-icon-weight:before { content: '\e734'; }
.wd-icon-health:before { content: '\e735'; }
.wd-icon-medical:before { content: '\e736'; }
.wd-icon-hospital:before { content: '\e737'; }
.wd-icon-pharmacy:before { content: '\e738'; }
.wd-icon-pill:before { content: '\e739'; }
.wd-icon-medicine:before { content: '\e73a'; }
.wd-icon-first-aid:before { content: '\e73b'; }
.wd-icon-emergency:before { content: '\e73c'; }
.wd-icon-alert:before { content: '\e73d'; }
.wd-icon-warning:before { content: '\e73e'; }
.wd-icon-safe:before { content: '\e73f'; }
.wd-icon-shield:before { content: '\e740'; }
.wd-icon-security:before { content: '\e741'; }
.wd-icon-lock:before { content: '\e742'; }
.wd-icon-unlock:before { content: '\e743'; }
.wd-icon-key:before { content: '\e744'; }
.wd-icon-password:before { content: '\e745'; }
.wd-icon-login:before { content: '\e746'; }
.wd-icon-logout:before { content: '\e747'; }
.wd-icon-register:before { content: '\e748'; }
.wd-icon-signup:before { content: '\e749'; }
.wd-icon-subscribe:before { content: '\e74a'; }
.wd-icon-unsubscribe:before { content: '\e74b'; }
.wd-icon-follow:before { content: '\e74c'; }
.wd-icon-unfollow:before { content: '\e74d'; }
.wd-icon-friend:before { content: '\e74e'; }
.wd-icon-group:before { content: '\e74f'; }
.wd-icon-team:before { content: '\e750'; }
.wd-icon-collaboration:before { content: '\e751'; }
.wd-icon-cooperation:before { content: '\e752'; }
.wd-icon-partnership:before { content: '\e753'; }
.wd-icon-network:before { content: '\e754'; }
.wd-icon-community:before { content: '\e755'; }
.wd-icon-forum:before { content: '\e756'; }
.wd-icon-chat:before { content: '\e757'; }
.wd-icon-conversation:before { content: '\e758'; }
.wd-icon-discussion:before { content: '\e759'; }
.wd-icon-debate:before { content: '\e75a'; }
.wd-icon-meeting:before { content: '\e75b'; }
.wd-icon-conference:before { content: '\e75c'; }
.wd-icon-presentation:before { content: '\e75d'; }
.wd-icon-speech:before { content: '\e75e'; }
.wd-icon-lecture:before { content: '\e75f'; }
.wd-icon-seminar:before { content: '\e760'; }
.wd-icon-workshop:before { content: '\e761'; }
.wd-icon-training:before { content: '\e762'; }
.wd-icon-education:before { content: '\e763'; }
.wd-icon-learning:before { content: '\e764'; }
.wd-icon-study:before { content: '\e765'; }
.wd-icon-exam:before { content: '\e766'; }
.wd-icon-test:before { content: '\e767'; }
.wd-icon-quiz:before { content: '\e768'; }
.wd-icon-homework:before { content: '\e769'; }
.wd-icon-assignment:before { content: '\e76a'; }
.wd-icon-project:before { content: '\e76b'; }
.wd-icon-task:before { content: '\e76c'; }
.wd-icon-todo:before { content: '\e76d'; }
.wd-icon-checklist:before { content: '\e76e'; }
.wd-icon-calendar:before { content: '\e76f'; }
.wd-icon-schedule:before { content: '\e770'; }
.wd-icon-timetable:before { content: '\e771'; }
.wd-icon-planner:before { content: '\e772'; }
.wd-icon-reminder:before { content: '\e773'; }
.wd-icon-alarm:before { content: '\e774'; }
.wd-icon-clock:before { content: '\e775'; }
.wd-icon-timer:before { content: '\e776'; }
.wd-icon-stopwatch:before { content: '\e777'; }
.wd-icon-hourglass:before { content: '\e778'; }
.wd-icon-watch:before { content: '\e779'; }
.wd-icon-weather:before { content: '\e77a'; }
.wd-icon-sunny:before { content: '\e77b'; }
.wd-icon-cloudy:before { content: '\e77c'; }
.wd-icon-rainy:before { content: '\e77d'; }
.wd-icon-snowy:before { content: '\e77e'; }
.wd-icon-windy:before { content: '\e77f'; }
.wd-icon-storm:before { content: '\e780'; }
.wd-icon-fog:before { content: '\e781'; }
.wd-icon-humidity:before { content: '\e782'; }
.wd-icon-temperature:before { content: '\e783'; }
.wd-icon-thermometer:before { content: '\e784'; }
.wd-icon-sun:before { content: '\e785'; }
.wd-icon-moon:before { content: '\e786'; }
.wd-icon-star:before { content: '\e787'; }
.wd-icon-cloud:before { content: '\e788'; }
.wd-icon-rain:before { content: '\e789'; }
.wd-icon-snow:before { content: '\e78a'; }
.wd-icon-wind:before { content: '\e78b'; }
.wd-icon-lightning:before { content: '\e78c'; }
.wd-icon-thunder:before { content: '\e78d'; }
.wd-icon-tornado:before { content: '\e78e'; }
.wd-icon-hurricane:before { content: '\e78f'; }
.wd-icon-earthquake:before { content: '\e790'; }
.wd-icon-volcano:before { content: '\e791'; }
.wd-icon-flood:before { content: '\e792'; }
.wd-icon-drought:before { content: '\e793'; }
.wd-icon-fire:before { content: '\e794'; }
.wd-icon-smoke:before { content: '\e795'; }
.wd-icon-pollution:before { content: '\e796'; }
.wd-icon-recycle:before { content: '\e797'; }
.wd-icon-leaf:before { content: '\e798'; }
.wd-icon-tree:before { content: '\e799'; }
.wd-icon-flower:before { content: '\e79a'; }
.wd-icon-grass:before { content: '\e79b'; }
.wd-icon-plant:before { content: '\e79c'; }
.wd-icon-nature:before { content: '\e79d'; }
.wd-icon-environment:before { content: '\e79e'; }
.wd-icon-ecology:before { content: '\e79f'; }
.wd-icon-green:before { content: '\e7a0'; }
.wd-icon-sustainable:before { content: '\e7a1'; }
.wd-icon-energy:before { content: '\e7a2'; }
.wd-icon-solar:before { content: '\e7a3'; }
.wd-icon-wind-energy:before { content: '\e7a4'; }
.wd-icon-hydro:before { content: '\e7a5'; }
.wd-icon-geothermal:before { content: '\e7a6'; }
.wd-icon-biomass:before { content: '\e7a7'; }
.wd-icon-nuclear:before { content: '\e7a8'; }
.wd-icon-coal:before { content: '\e7a9'; }
.wd-icon-oil:before { content: '\e7aa'; }
.wd-icon-gas:before { content: '\e7ab'; }
.wd-icon-electricity:before { content: '\e7ac'; }
.wd-icon-battery:before { content: '\e7ad'; }
.wd-icon-charge:before { content: '\e7ae'; }
.wd-icon-plug:before { content: '\e7af'; }
.wd-icon-socket:before { content: '\e7b0'; }
.wd-icon-light:before { content: '\e7b1'; }
.wd-icon-bulb:before { content: '\e7b2'; }
.wd-icon-lamp:before { content: '\e7b3'; }
.wd-icon-flashlight:before { content: '\e7b4'; }
.wd-icon-torch:before { content: '\e7b5'; }
.wd-icon-candle:before { content: '\e7b6'; }
.wd-icon-fire:before { content: '\e7b7'; }
.wd-icon-flame:before { content: '\e7b8'; }
.wd-icon-heat:before { content: '\e7b9'; }
.wd-icon-cold:before { content: '\e7ba'; }
.wd-icon-snowflake:before { content: '\e7bb'; }
.wd-icon-ice:before { content: '\e7bc'; }
.wd-icon-frost:before { content: '\e7bd'; }
.wd-icon-cool:before { content: '\e7be'; }
.wd-icon-warm:before { content: '\e7bf'; }
.wd-icon-hot:before { content: '\e7c0'; }
.wd-icon-thermometer:before { content: '\e7c1'; }
.wd-icon-temperature:before { content: '\e7c2'; }
.wd-icon-weather:before { content: '\e7c3'; }
.wd-icon-sun:before { content: '\e7c4'; }
.wd-icon-moon:before { content: '\e7c5'; }
.wd-icon-star:before { content: '\e7c6'; }
.wd-icon-cloud:before { content: '\e7c7'; }
.wd-icon-rain:before { content: '\e7c8'; }
.wd-icon-snow:before { content: '\e7c9'; }
.wd-icon-wind:before { content: '\e7ca'; }
.wd-icon-lightning:before { content: '\e7cb'; }
.wd-icon-thunder:before { content: '\e7cc'; }
.wd-icon-tornado:before { content: '\e7cd'; }
.wd-icon-hurricane:before { content: '\e7ce'; }
.wd-icon-earthquake:before { content: '\e7cf'; }
.wd-icon-volcano:before { content: '\e7d0'; }
.wd-icon-flood:before { content: '\e7d1'; }
.wd-icon-drought:before { content: '\e7d2'; }
.wd-icon-fire:before { content: '\e7d3'; }
.wd-icon-smoke:before { content: '\e7d4'; }
.wd-icon-pollution:before { content: '\e7d5'; }
.wd-icon-recycle:before { content: '\e7d6'; }
.wd-icon-leaf:before { content: '\e7d7'; }
.wd-icon-tree:before { content: '\e7d8'; }
.wd-icon-flower:before { content: '\e7d9'; }
.wd-icon-grass:before { content: '\e7da'; }
.wd-icon-plant:before { content: '\e7db'; }
.wd-icon-nature:before { content: '\e7dc'; }
.wd-icon-environment:before { content: '\e7dd'; }
.wd-icon-ecology:before { content: '\e7de'; }
.wd-icon-green:before { content: '\e7df'; }
.wd-icon-sustainable:before { content: '\e7e0'; }
.wd-icon-energy:before { content: '\e7e1'; }
.wd-icon-solar:before { content: '\e7e2'; }
.wd-icon-wind-energy:before { content: '\e7e3'; }
.wd-icon-hydro:before { content: '\e7e4'; }
.wd-icon-geothermal:before { content: '\e7e5'; }
.wd-icon-biomass:before { content: '\e7e6'; }
.wd-icon-nuclear:before { content: '\e7e7'; }
.wd-icon-coal:before { content: '\e7e8'; }
.wd-icon-oil:before { content: '\e7e9'; }
.wd-icon-gas:before { content: '\e7ea'; }
.wd-icon-electricity:before { content: '\e7eb'; }
.wd-icon-battery:before { content: '\e7ec'; }
.wd-icon-charge:before { content: '\e7ed'; }
.wd-icon-plug:before { content: '\e7ee'; }
.wd-icon-socket:before { content: '\e7ef'; }
.wd-icon-light:before { content: '\e7f0'; }
.wd-icon-bulb:before { content: '\e7f1'; }
.wd-icon-lamp:before { content: '\e7f2'; }
.wd-icon-flashlight:before { content: '\e7f3'; }
.wd-icon-torch:before { content: '\e7f4'; }
.wd-icon-candle:before { content: '\e7f5'; }
.wd-icon-fire:before { content: '\e7f6'; }
.wd-icon-flame:before { content: '\e7f7'; }
.wd-icon-heat:before { content: '\e7f8'; }
.wd-icon-cold:before { content: '\e7f9'; }
.wd-icon-snowflake:before { content: '\e7fa'; }
.wd-icon-ice:before { content: '\e7fb'; }
.wd-icon-frost:before { content: '\e7fc'; }
.wd-icon-cool:before { content: '\e7fd'; }
.wd-icon-warm:before { content: '\e7fe'; }
.wd-icon-hot:before { content: '\e7ff'; }
</style>